services:
  - type: web
    name: ai-recommender-ecommerce
    env: python
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt --no-cache-dir --no-deps
      pip install -r requirements.txt --no-cache-dir
    startCommand: |
      cd ecommerce_project
      export PYTHONPATH=/opt/render/project/src
      export DJANGO_SETTINGS_MODULE=ecommerce_project.settings
      gunicorn ecommerce_project.wsgi:application --bind 0.0.0.0:$PORT --workers 4
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.12
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: MONGODB_URI
        sync: false
        required: true
      - key: DEBUG
        value: "False" 