# Generated by Django 4.1.13 on 2025-05-03 09:22

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=djongo.models.fields.JSONField(blank=True, default=list),
        ),
    ]
